/**
 * Meme card pool management utilities
 * Handles the 800+ meme images from /public/memes/
 */

// Cache for meme card data
let memeCardCache: MemeCard[] | null = null;

/**
 * Generates a MemeCard object from a filename
 */
function createMemeCard(filename: string): MemeCard {
  // Remove file extension for ID
  const id = filename.replace(/\.(jpg|jpeg|png|gif|webp)$/i, "");

  return {
    id,
    filename,
    url: `/memes/${encodeURIComponent(filename)}`,
    alt: `Meme: ${id.replace(/[_-]/g, " ")}`,
  };
}

/**
 * List of all meme filenames (comprehensive list from the memes directory)
 */
const MEME_FILENAMES = [
  "1618525445959.png",
  "A golden experience for my eyes.jpg",
  "Abraham.jpg",
  "Absolutely disgusting.jpg",
  "Activated intant kill.jpg",
  "Adios.jpg",
  "Ah ah yes.jpg",
  "Ah shit here we go again GTA.jpg",
  "Ah yes finally nigerundayo.jpg",
  "All weapons.jpg",
  "Am I a joke to you.jpg",
  "Anaïs.jpg",
  "Analise.jpg",
  "Angry doge.jpg",
  "Angry kid.jpg",
  "Angry Pakistani Fan.jpg",
  "Angry pinguin.jpg",
  "Angry rabbit.jpg",
  "Angry scientist noises.jpg",
  "Angry stand.jpg",
  "Animal crossing clown.jpg",
  "Anime glasses.jpg",
  "Apruv.jpg",
  "Are you braindead.png",
  "Arrivederchi.jpg",
  "art.jpg",
  "Baby yoda crying.jpg",
  "Baby Yoda sipping soup.jpg",
  "Balais couille.jpg",
  "Banjo.jpg",
  "Bart 1.jpg",
  "Bart 2.jpg",
  "Bart.jpg",
  "Bébé 1.jpg",
  "Bébé 2.jpg",
  "Bébé wtf.jpg",
  "Bebe Yoda gun.jpg",
  "Bébé yoda.jpg",
  "Bee movie.jpg",
  "Berserk.jpg",
  "Big balls.jpg",
  "Big brain kowalski.jpg",
  "Big brain time.jpg",
  "Bigflo.jpg",
  "Bitch what the fuck Laton.jpg",
  "Bitch what the fuck.jpg",
  "Bitch what.jpg",
  "Bois Bob l_éponge.jpg",
  "Bois chien.jpg",
  "Bois Giorno.jpg",
  "Bois Inkling.jpg",
  "Bois Kermit.jpg",
  "Bois Lisa.jpg",
  "Bois Mista.jpg",
  "Bois Poisson de bob l_éponge.jpg",
  "Bois Violette.jpg",
  "Bois Zuckerberg.jpg",
  "Brainlet 1.jpg",
  "Brainlet 10.jpg",
  "Brainlet 11.jpg",
  "Brainlet 12.jpg",
  "Brainlet 13.jpg",
  "Brainlet 14.jpg",
  "Brainlet 15.jpg",
  "Brainlet 16.jpg",
  "Brainlet 17.jpg",
  "Brainlet 18.jpg",
  "Brainlet 19.jpg",
  "Brainlet 2.jpg",
  "Brainlet 20.jpg",
  "Brainlet 21.jpg",
  "Brainlet 22.jpg",
  "Brainlet 23.jpg",
  "Brainlet 24.jpg",
  "Brainlet 25.jpg",
  "Brainlet 26.jpg",
  "Brainlet 27.jpg",
  "Brainlet 28.jpg",
  "Brainlet 29.jpg",
  "Brainlet 3.jpg",
  "Brainlet 30.jpg",
  "Brainlet 31.jpg",
  "Brainlet 32.jpg",
  "Brainlet 33.jpg",
  "Brainlet 34.jpg",
  "Brainlet 35.jpg",
  "Brainlet 36.jpg",
  "Brainlet 4.jpg",
  "Brainlet 5.jpg",
  "Brainlet 6.jpg",
  "Brainlet 7.jpg",
  "Brainlet 8.jpg",
  "Brainlet 9.jpg",
  "Breins.jpg",
  "Brindibou.jpg",
  "Bruh.jpg",
  "Bruno choqué.jpg",
  "Bruno hearts.jpg",
  "Bruno you dropped this.jpg",
  "Bugs bunny.jpg",
  "C_est quoi ce bordel.jpg",
  "Calm down calm down.jpg",
  "Captain Falcon.jpg",
  "Carlos 1.jpg",
  "Carlos 2.jpg",
  "Carlos et Krabs.jpg",
  "Carlos loser.jpg",
  "Carlos.jpg",
  "Cat chat défonsé stone high.png",
  "Cat reload.jpg",
  "Certified idiot.jpg",
  "Chat 1.jpg",
  "Chat 10.jpg",
  "Chat 11.jpg",
  "Chat 12.jpg",
  "Chat 13.jpg",
  "Chat 14.jpg",
  "Chat 15.jpg",
  "Chat 16.jpg",
  "Chat 17.jpg",
  "Chat 18.jpg",
  "Chat 19.jpg",
  "Chat 2.jpg",
  "Chat 20.jpg",
  "Chat 21.jpg",
  "Chat 22.jpg",
  "Chat 23.jpg",
  "Chat 24.jpg",
  "Chat 25.jpg",
  "Chat 26.jpg",
  "Chat 27.jpg",
  "Chat 28.jpg",
  "Chat 29.jpg",
  "Chat 3.jpg",
  "Chat 30.jpg",
  "Chat 31.jpg",
  "Chat 4.jpg",
  "Chat 5.jpg",
  "Chat 7.jpg",
  "Chat 8.jpg",
  "Chat 9.jpg",
  "chat choqué surpris.jpg",
  "Chat.jpg",
  "Cheers i_ll drink to that bro.jpg",
  "Chess echecs Knight takes pawn rook takes knight.jpg",
  "Chien 1.jpg",
  "Chien 2.jpg",
  "Chien 3.jpg",
  "Chien braqueur.jpg",
  "Chien content.jpg",
  "Chien trauma chihuahua guerre helicoptere Vietnam dog.jpg",
  "Chien.jpg",
  "Choqué de la brutalité.jpg",
  "Chubby bubbles girl fille fillette bulles jaune court.jpg",
  "Clever thoughts penser think dire tell.jpg",
  "Clown Carlos.jpg",
  "Clown detector.jpg",
  "Clown hentai.jpg",
  "Clown license.jpg",
  "Clown pc.jpg",
  "Clown ronald.jpg",
  "Clown sad emoji.jpg",
  "Clown to clown communication.jpg",
  "Clown university invitation.jpg",
  "Clown Wojak.jpg",
  "Clown.jpg",
  "Club Penguin ban.jpg",
  "Comedy gold.jpg",
  "Confused cat.jpg",
  "confused ora.jpg",
  "Confused screaming.jpg",
  "Confused Shoto.jpg",
  "Confused stonks.jpg",
  "Crachat d_eau.jpg",
  "Creeper.jpg",
  "Cries in JoJo.jpg",
  "Crise cardiaque.jpg",
  "Crying baby pep talk.jpg",
  "Crying Cat Template _ Schmuserkadser - Chat.jpg",
  "Crying kid.jpg",
  "Cursed Cat _ Angry As Fuk _ ъуъ съука.jpg",
  "Cursed emoji.jpg",
  "Cursed pikachu.jpg",
  "Cut.jpg",
  "da fuck they doin ova der.jpg",
  "Dadidou 1.jpg",
  "Dadidou 2.jpg",
  "Dadidou 3.jpg",
  "Daisy looking at you.jpg",
  "Daisy Ridley pointing femme pointe doigt feuille.jpg",
  "Damn I kinda don_t care.jpg",
  "Darwin.jpg",
  "De l_air jpp.jpg",
  "Dear God.jpg",
  "Detectiv.jpg",
  "Difficult situation.jpg",
  "Dio gun.jpg",
  "Dio sending heart.jpg",
  "Dio vs Jotaro.jpg",
  "Diplôme du QI négatif.jpg",
  "Dirigeants regardant la caméra.jpg",
  "Disappointed but not surprised.jpg",
  "Discord guy.jpg",
  "Discovering something that doesn't exist.jpg",
  "Disparition.jpg",
  "Do you have brain damage.jpg",
  "Dog hearts.jpg",
  "Doge looking at you.jpg",
  "Doge triste.jpg",
  "Doigt et mouchoir.jpg",
  "Don_t give me hope.jpg",
  "Donald.jpg",
  "Donkey kong.jpg",
  "Doppio heurts.jpg",
  "Dormir 1.jpg",
  "Dormir 11.jpg",
  "Dormir 2.jpg",
  "Dormir 3.jpg",
  "Dormir 4.jpg",
  "Dormir 5.jpg",
  "Dormir 6.jpg",
  "Dormir 7.jpg",
  "Dormir 8.jpg",
  "Dormir 9.jpg",
  "Douche chat triste.jpg",
  "Dr Eggman.jpg",
  "Dr Stone choqué.jpg",
  "Dr Stone gêne.jpg",
  "Dr Stonk.jpg",
  "Dust Storm Dog tempete sable cheems doge ville city.jpg",
  "Eau dans les yeux.jpg",
  "Ecraser tomber Fuze elbow dropping a hostage.jpg",
  "Emoji 1.jpg",
  "Emoji 10.jpg",
  "Emoji 11.jpg",
  "Emoji 12.jpg",
  "Emoji 13.jpg",
  "Emoji 14.jpg",
  "Emoji 15.jpg",
  "Emoji 16.jpg",
  "Emoji 17.jpg",
  "Emoji 18.jpg",
  "Emoji 2.jpg",
  "Emoji 3.jpg",
  "Emoji 4.jpg",
  "Emoji 5.jpg",
  "Emoji 6.jpg",
  "Emoji 7.jpg",
  "Emoji 8.jpg",
  "Emoji 9.jpg",
  "Emoji soleil.jpg",
  "Emoji.jpg",
  "Emojis laugh.jpg",
  "Enfant étranglé.jpg",
  "Everyone is stupid except me.jpg",
  "Excuse me what the fuck.jpg",
  "Excuse me wtf.jpg",
  "Excusez-moi quoi de la fuck.jpg",
  "Expanding brain cerveau mind 2.jpg",
  "Expanding brain cerveau mind 3.jpg",
  "Facts.jpg",
  "Family Guy 1.jpg",
  "Family Guy 2.jpg",
  "Family guy dog.jpg",
  "FBI.jpg",
  "Feels good.jpg",
  "Filosof.jpg",
  "Finally, some good fucking news.jpg",
  "Find who tf asked.jpg",
  "Finger in ass - fesses doigt cul.jpg",
  "Fire rescue - feu incendie choisir sauver.jpg",
  "Flex tape ad Phil swift slaps on flex scotch eau coule .jpg",
  "Flynn entouré d_épées.jpg",
  "Forgiveness stop.jpg",
  "Friends.jpg",
  "fuk.png",
  "Furry vs dog.jpg",
  "G dead ça chakal.jpg",
  "Galactic oof.jpg",
  "Garfield & cie.jpg",
  "Genius.jpg",
  "Get therapy please.jpg",
  "Giorno looking at his phone.jpg",
  "Giorno uno heart.jpg",
  "Giorno you dropped this.jpg",
  "Giorno.jpg",
  "Girls getting wetter about exciter fontaine mouiller chaude.jpg",
  "Give me a reason to live.jpg",
  "Glasses.jpg",
  "Goche Droate.jpg",
  "Golden Wind 1.jpg",
  "Golden Wind 2.jpg",
  "Gon and Killua.jpg",
  "Good job don_t give up etc.jpg",
  "Grandma hiding knife from rabbit mamie grand mere couteau lapin.jpg",
  "Gravity fall feuille papier lire paper read.jpg",
  "Grenouille trophé.jpg",
  "Greta 1.jpg",
  "Greta 2.jpg",
  "Griffin - familly guy - Better than me.jpg",
  "Gru pointing gun.jpg",
  "Gudim - noyer secours main tape chek aider Drowning high five.jpg",
  "Gumball 1.jpg",
  "Gumball 2.jpg",
  "Gumball 3.jpg",
  "Gumball et Darwin 1.jpg",
  "Gumball et Darwin 2.jpg",
  "Gumball et Darwin.jpg",
  "Gumball.jpg",
  "Hamster croix.jpg",
  "Hamster.jpg",
  "Happiness noise.webp",
  "Happy Luffy.jpg",
  "Harcelement école casier college black Bully guy.jpg",
  "Hard to swallow pills pilules médicaments avaler.jpg",
  "Harold 1.jpg",
  "Harold 2.jpg",
  "Harold 3.jpg",
  "Harold 4.jpg",
  "Harold 5.jpg",
  "Harold 6.jpg",
  "Harold.jpg",
  "Harvard wants to know your location.jpg",
  "He didn_t laugh.jpg",
  "He is speaking the language of the gods.jpg",
  "Help.jpg",
  "Here we go again clown.jpg",
  "Hérisson.jpg",
  "Hes about to do something stupid.jpg",
  "Hey king you dropped this.jpg",
  "Historia.jpg",
  "Hitler vs Staline.jpg",
  "hm.jpg",
  "Hold up.jpg",
  "Holy music stops.jpg",
  "Holy water.jpg",
  "Homer 1.jpg",
  "Homer 2.jpg",
  "Homer angry.jpg",
  "Homer et Marge.jpg",
  "Homer gordo.jpg",
  "Homer riche.jpg",
  "Homer.jpg",
  "Homme femme fragile sad man girls Do men even even have feelings.jpg",
  "Huge swole man ordering food.jpg",
  "Hulk Regretful regrets.jpg",
  "Hulk tacos.jpg",
  "Humm Villager.jpg",
  "i am dead ok.jpg",
  "I am looking directly at you.jpg",
  "i am proposing.jpg",
  "I dont want to live on this planet anymore.jpg",
  "I guess.jpg",
  "I hate everyone.jpg",
  "I have a question for god, why.jpg",
  "I have achieved comedy.jpg",
  "I know that feel bro.jpg",
  "I Miss Ten Seconds Ago.jpg",
  "I never lose.jpg",
  "I outsmarted your outsmarting Joseph.jpg",
  "I pretend I do not see it.jpg",
  "I see 1.jpg",
  "I see 2.jpg",
  "I see 3.jpg",
  "I see 4.jpg",
  "I see 5.jpg",
  "i sleep Real shit black.jpg",
  "I think I forgot something.jpg",
  "I want to dead.jpg",
  "I_ll be watching good luck.jpg",
  "I_m gonna have a breakdown breakdown.jpg",
  "I_m gonna stop you right there.jpg",
  "I_m throwing away my humanity Jojo.jpg",
  "I_ve looked at this for 5h now.jpg",
  "i_ve won, but at what cost.jpg",
  "idk dude, that was kinda offensive.jpg",
  "Impossible.jpg",
  "infinity IQ.jpg",
  "Injustice caricature riche pauvre capitalisme.jpg",
  "intellecc.jpg",
  "Interesting.jpg",
  "Is that a personal attack or something.jpg",
  "It_s the law.jpg",
  "Its blank kung ffu panda.jpg",
  "Izuku choqué.jpg",
  "Izuku looking at his phone.jpg",
  "J_entends rien.jpg",
  "J_retourne nehess.jpg",
  "Jake hurle.jpg",
  "Je ne dirais pas que c_est un échec je dirais que ça n_a pas marché.jpg",
  "Je suis dans la barbamerde.jpg",
  "Jean Pierre Palareff.jpg",
  "Jerry Golet.jpg",
  "Jerry smith looking through viewfinder.jpg",
  "Jerry.jpg",
  "JNR.jpg",
  "Joconde choquée.jpg",
  "Joey.jpg",
  "John Cena laughing.jpg",
  "John Wick.jpg",
  "Jojo emoji.jpg",
  "Jojo Whispering To Surprised Emma Roberts.jpg",
  "Joker All I have are negative thoughts.jpg",
  "Joker and Peter Parker dancing.jpg",
  "Joker dancing.jpg",
  "Joker sign slam.jpg",
  "Jonah hill dropping coffee.jpg",
  "Josuke.jpg",
  "Jotaro crying.jpg",
  "Jotaro sueur.jpg",
  "Kaguya choquée.jpg",
  "Kakyoin.jpg",
  "Kazuma.jpg",
  "Kermit 1.jpg",
  "Kermit 2.jpg",
  "Kermit 3.jpg",
  "Kermit 4.jpg",
  "Kermit 5.jpg",
  "Kermit 6.JPG",
  "Kermit étranglé.jpg",
  "Kermit suicide gun.jpg",
  "Kermit thinking.jpg",
  "Kermit.jpg",
  "King Crimson clown.jpg",
  "King k rool.jpg",
  "Kira sueur.jpg",
  "Kirby 1.jpg",
  "Kirby 2.jpg",
  "Kirby sign.jpg",
  "Kirby speech.jpg",
  "Koichi choqué.jpg",
  "Kombucha girl.jpg",
  "Krabs 1.jpg",
  "Krabs 2.jpg",
  "Krabs what the fuck.jpg",
  "Krabs, Carlos, Bob et Patrick.jpg",
  "Krabs.jpg",
  "Kungfu panda.jpg",
  "Kuzco.jpg",
  "laughing emoji costume gun.jpg",
  "Lavage d_yeux.jpg",
  "Le turfu.jpg",
  "Lelouche.jpg",
  "Let_s keep this on.jpg",
  "Like et RT 1.jpg",
  "Like et RT 2.jpg",
  "Like et RT 3.jpg",
  "Like et RT 4.jpg",
  "Like et RT 5.jpg",
  "Link.jpg",
  "Lisa angry.jpg",
  "Lisa.jpg",
  "Listen here, you little shit.jpg",
  "Livaï gun on you.jpg",
  "Livaï what the fuck.jpg",
  "Loading cat.jpg",
  "Look how they massacred my boy.jpg",
  "Love and affection.jpg",
  "Love and support.jpg",
  "Love juice.jpg",
  "Luffy.jpg",
  "Luigi blasé.jpg",
  "Luigi looking at his phone.jpg",
  "Luigi.jpg",
  "Madagascar pinguoin.jpg",
  "Mafs.jpg",
  "Mama mia.jpg",
  "Man smacking cards down on table cartes.jpg",
  "Marge gênée.jpg",
  "Marge qui tombe.jpg",
  "Marge, Homer et Lisa.jpg",
  "Marge.jpg",
  "Mario 1.jpg",
  "Mario 2.jpg",
  "Mario clown 1.jpg",
  "Mario clown 2.jpg",
  "Mario clown 3.jpg",
  "Mario clown 4.jpg",
  "Mario et Luigi.jpg",
  "Mario nu.jpg",
  "Mario.jpg",
  "masterclass.jpg",
  "Masters blessing chevalier epee.jpg",
  "Mdr g pa Lu.jpg",
  "Mdr man.jpg",
  "Mdr truck.jpg",
  "Megumin.jpg",
  "Mei No.jpg",
  "Meme lord Elon laugh.jpg",
  "Mère poisson choquée 1.jpg",
  "Mère poisson choquée 2.jpg",
  "Messi.jpg",
  "Mickey 1.jpg",
  "Mickey 2.jpg",
  "Mickey.jpg",
  "Mince.jpg",
  "Mind size.jpg",
  "Minecarft craft.jpg",
  "Minecraft apple.jpg",
  "Minecraft furnace.jpg",
  "Minecraft ores.jpg",
  "Miroir chauffage sourir.jpg",
  "Mista sad.jpg",
  "Mister V.jpg",
  "Moe 1.jpg",
  "Moe 2.jpg",
  "Moe.jpg",
  "Mom comme pick me up.jpg",
  "Monika T-Posing over Sans.jpg",
  "Mont Rushmore choqué.jpg",
  "Moon better.jpg",
  "Morty 2.jpg",
  "Morty.jpg",
  "Mouchoir.jpg",
  "Mr propre.jpg",
  "Multi characters mug.jpg",
  "Multiple conducteurs choqués 1.jpg",
  "Multiple conducteurs choqués 2.jpg",
  "My eyes.jpg",
  "my goals are beyond your understanding.jpg",
  "My heart is broken.jpg",
  "My IQ it_s 3.jpg",
  "My love for you U3.jpg",
  "Narancia hearts.jpg",
  "Naruto hiding.jpg",
  "Naruto.jpg",
  "Ne sais pas.jpg",
  "Neji confused.jpg",
  "Nemo dad.jpg",
  "Nerf fusil à pompe.jpg",
  "Next you_ll say Joseph.jpg",
  "Next you_ll say, I was only pretending to be a clown.jpg",
  "Nice Bee movie.jpg",
  "Nick fury looks at pink guy homme combinaison rose voiture.jpg",
  "Nicole.jpg",
  "nike zebi j_me casse.jpg",
  "Ninja turtles growing up tortue splinter.jpg",
  "No one cares 1.jpg",
  "No one cares 2.jpg",
  "No sign of intelligent life.jpg",
  "Noah get the boat.jpg",
  "non.jpg",
  "Not bad kid.jpg",
  "Not funny didn_t laugh Giorno.jpg",
  "Not funny didn_t laugh Gru.jpg",
  "Not funny didn_t laugh Josuke.jpg",
  "Not stonks.jpg",
  "Not today old friend.jpg",
  "Not yet Ferb.jpg",
  "Now that_s I_m talking about.jpg",
  "Obama auto congratulate.jpg",
  "Oh boy, here I go killing again.jpg",
  "Oh no.jpg",
  "Oh youre a villain alright just not a super one.jpg",
  "Okay but it_s not what I wanted.jpg",
  "Old Hulk vs new Hulk.jpg",
  "Oof 1.jpg",
  "Oof 2.jpg",
  "Oof 3.jpg",
  "Oof size.jpg",
  "Oof stone.jpg",
  "Oui j_ai fait la pute.jpg",
  "Outstanding move.jpg",
  "Pain 1.jpg",
  "Pain 2.jpg",
  "Pain horse.jpg",
  "Pasta la vista.jpg",
  "Patrick 1.jpg",
  "Patrick 2.jpg",
  "Patrick 3.jpg",
  "Patrick 4.jpg",
  "Patrick.jpg",
  "Peau chuchottement murmurer cahir de poule poils.jpg",
  "Penseur spatio-temporel 1.jpg",
  "Penseur spatio-temporel 2.jpg",
  "Pepe 1.jpg",
  "Pepe 10.jpg",
  "Pepe 2.jpg",
  "Pepe 3.jpg",
  "Pepe 4.jpg",
  "Pepe 6.jpg",
  "Pepe 7.jpg",
  "Pepe 8.jpg",
  "Pepe 9.jpg",
  "Pepe clown 1.jpg",
  "Pepe clown 2.jpg",
  "Pepe enough.jpg",
  "Pepe Jesus.jpg",
  "Pepe.jpg",
  "Perfection.jpg",
  "Perhaps.jpg",
  "Peter Parker blasé.jpg",
  "Piano music stops.jpg",
  "Pikachu 1.jpg",
  "Pikachu 2.jpg",
  "Pikachu 3.jpg",
  "Pikachu 4.jpg",
  "Pikachu caprisun.jpg",
  "Pikachu.jpg",
  "Pirate.jpg",
  "Pleased Sully.jpg",
  "Poing haki.jpg",
  "Pointe avec un fusil.jpg",
  "Poisson bob l_éponge 1.jpg",
  "Poisson bob l_éponge 2.jpg",
  "Poisson de bob l_éponge 1.jpg",
  "Poisson de bob l_éponge 2.jpg",
  "Poisson de bob l_éponge 3.jpg",
  "Poisson de bob l_éponge choqué.jpg",
  "Poisson de Bob l_éponge.jpg",
  "Pokémon 1.jpg",
  "Pokémon 2.jpg",
  "Pokémon.jpg",
  "Police cop crs courir manifestant Running away from area 51.jpg",
  "Polnareff et Abdul.jpg",
  "Poussin couteau.jpg",
  "Poussin.jpg",
  "POV girls 1.jpg",
  "Primitive Spongebob.jpg",
  "Professional retard.jpg",
  "Proto Yes.jpg",
  "ptn zbi.jpg",
  "Putain zebi.jpg",
  "Putting on clown makeup maquillage.jpg",
  "Que faire des cons.jpg",
  "Quentin Tarantino walking around.jpg",
  "Rasengun.jpg",
  "Razowski 1.jpg",
  "Razowski 2.jpg",
  "Razowski.jpg",
  "Regular show 1.jpg",
  "Regular show 2.jpg",
  "Regular show 3.jpg",
  "Repost if you_re stupid.jpg",
  "Restraining order.jpg",
  "Rick 1.jpg",
  "Rick 2.jpg",
  "Rick Morty adventure card.jpg",
  "Rick.jpg",
  "Roi Carlos.jpg",
  "Sacha triste.jpg",
  "Sad dog.jpg",
  "Sad gaming cat.jpg",
  "Sad homer.jpg",
  "Sad Luffy.jpg",
  "Sad Morty.jpg",
  "Sad party emoji.jpg",
  "Sad racoon.jpg",
  "Sad Spiderman.jpg",
  "Sad Yoshi.jpg",
  "Sam.jpg",
  "Sans nom 1.jpg",
  "Sans nom 10.jpg",
  "Sans nom 11.jpg",
  "Sans nom 12.jpg",
  "Sans nom 13.jpg",
  "Sans nom 14.jpg",
  "Sans nom 15.jpg",
  "Sans nom 16.jpg",
  "Sans nom 17.jpg",
  "Sans nom 18.jpg",
  "Sans nom 19.jpg",
  "Sans nom 2.jpg",
  "Sans nom 20.jpg",
  "Sans nom 21.jpg",
  "Sans nom 22.jpg",
  "Sans nom 23.jpg",
  "Sans nom 24.jpg",
  "Sans nom 25.jpg",
  "Sans nom 26.jpg",
  "Sans nom 27.jpg",
  "Sans nom 29.jpg",
  "Sans nom 3.jpg",
  "Sans nom 30.jpg",
  "Sans nom 31.jpg",
  "Sans nom 32.jpg",
  "Sans nom 33.jpg",
  "Sans nom 35.jpg",
  "Sans nom 36.jpg",
  "Sans nom 37.jpg",
  "Sans nom 38.jpg",
  "Sans nom 39.jpg",
  "Sans nom 4.jpg",
  "Sans nom 40.jpg",
  "Sans nom 41.jpg",
  "Sans nom 42.jpg",
  "Sans nom 43.jpg",
  "Sans nom 44.jpg",
  "Sans nom 5.jpg",
  "Sans nom 6.jpg",
  "Sans nom 7.jpg",
  "Sans nom 8.jpg",
  "Sans nom 9.jpg",
  "Sardoche gun.jpg",
  "Sardoche.jpg",
  "Sasuke 1.jpg",
  "Sasuke 2.jpg",
  "Sasuke love.jpg",
  "Sasuke smile.jpg",
  "Sasuke.jpg",
  "Scoubidou reveal.jpg",
  "Serrage de mains.jpg",
  "Shaggy.jpg",
  "Shit went from 0 to 100 real quick.jpg",
  "Shrek 1.jpg",
  "Shrek 2.jpg",
  "Shrek.jpg",
  "Shrugging Tom HD Redraw - Tom and Jerry - u_Gibus_Squidward on Reddit.jpg",
  "Shy truck.jpg",
  "Siense.jpg",
  "Silence.jpg",
  "Simpsons 1.jpg",
  "Simpsons 2.jpg",
  "Simpsons 3.jpg",
  "Simpsons 4.jpg",
  "Simpsons 5.jpg",
  "Simpsons 6.jpg",
  "SJW PC.jpg",
  "Skidaddle skidoodle.jpg",
  "Skipper.jpg",
  "Small brain vs big brain petit gros cerveau.jpg",
  "Smash.jpg",
  "Smile through the pain.jpg",
  "Smort.jpg",
  "Snas nom 7.jpg",
  "SNK.jpg",
  "So you have chosen death.jpg",
  "Soap on the floor savon savonette douche ramasse.jpg",
  "Soda fountain mix.jpg",
  "Soft mutilation.jpg",
  "Soldat.jpg",
  "Soldiers WW2.jpg",
  "Sorry sorry.jpg",
  "Soufflement de nez.jpg",
  "Souris part 1.jpg",
  "Souris part 2.jpg",
  "Soyjak fans vs Chad fans.jpg",
  "Spell red.jpg",
  "Spice adams hiding behind a tree.jpg",
  "Spider-Man explaining to Zendaya.jpg",
  "Spiderman 1.jpg",
  "Spiderman 2.jpg",
  "Spiderman 3.jpg",
  "Spiderman 4.jpg",
  "Spiderman hey.jpg",
  "Spiderman.jpg",
  "sponge bob l_eponge fenetre windows Carlos.jpg",
  "Spongebob 1.jpg",
  "Spongebob 2.jpg",
  "Spongebob cleaning his eyes.jpg",
  "Spongebob fish.jpg",
  "Spongebob horny.jpg",
  "Spongebob running away.jpg",
  "Spongebob square pants Bob l_éponge - Carlos 1.jpg",
  "Spongebob square pants Bob l_éponge - Carlos 2.jpg",
  "Spongebob square pants Bob l_éponge - Carlos 3.jpg",
  "Spongebob square pants Bob l_éponge - How many diapers could possibly use.jpg",
  "Spongebob square pants Bob l_éponge How original.jpg",
  "Spongebob square pants Bob l_éponge paye.jpg",
  "Spongebob square pants Bob l_éponge scared of the flying dutchman.jpg",
  "Spongebob square pants Bob l_éponge selling items stand vente foule.jpg",
  "Spongebob square pants Bob l_éponge Squidwards clock closet montre heure.jpg",
  "Spongebob square pants feu feuille bruler Bob l_éponge.jpg",
  "srgrafo - Dumbest man alive.jpg",
  "SrGrafo - Giants looking at a peasant geants bleu orange dieux gods.jpg",
  "SrGrafo - homme femme dire oreille orgasme fontaine mouiller exciter.jpg",
  "SrGrafo - Only someone stupid would fall for that.jpg",
  "SrGrafo - Preaching to the mob.jpg",
  "SrGrafo - Smartest man alive.jpg",
  "SS Oof 100.jpg",
  "SS Restoration 100.jpg",
  "SS Speech 100.jpg",
  "Star Trek choqué.jpg",
  "Star wars Dark Maul saber.jpg",
  "Starfoullah water.jpg",
  "Statue.jpg",
  "Steve pendu.jpg",
  "Steve.jpg",
  "Stonks.jpg",
  "Stop he_s already dead.jpg",
  "Stranger things Robin holding a whiteboard feuille marin matelot.jpg",
  "Suicidal thoughts.jpg",
  "Suicide adapter.jpg",
  "Suicide arc.jpg",
  "Suicide golem.jpg",
  "Suicide Moe.jpg",
  "Suicide.jpg",
  "Suicidez le.jpg",
  "Surprise motherfucker.jpg",
  "Surprised Joji.jpg",
  "Surprised Pikachu.jpg",
  "Suspicious spongebob.jpg",
  "Swole doge Jotaro  vs cheems.jpg",
  "Tanjiro.jpg",
  "Teddy bear looking at someone.jpg",
  "Tenma Gabriel.jpg",
  "Thank you all for coming.jpg",
  "Thank you, random citizen.jpg",
  "That shit you just posted.jpg",
  "That wasn_t part of my plan.jpg",
  "That_s crazy nobody asked.jpg",
  "That_s the joke.jpg",
  "The evilest thing.jpg",
  "The expert.jpg",
  "The Jig dance .jpg",
  "The return of the king.jpg",
  "TheKairi78.jpg",
  "These are confusing times.jpg",
  "This conversation_s so hight-IQ.jpg",
  "This is bait of excellent quality.jpg",
  "This is not okie dokie.jpg",
  "This isn_t a bruh moment at this point.jpg",
  "This say a lot about society.jpg",
  "Thomas had never seen such bullshit before.jpg",
  "Thomas Ngijol.jpg",
  "Timmy emoji.jpg",
  "Timmy.jpg",
  "Titan bestial.jpg",
  "Toad.jpg",
  "Tom .jpg",
  "Tom 1.jpg",
  "Tom 2.jpg",
  "Tom 3.jpg",
  "Tom Holland.jpg",
  "Tom jerry swole big small.jpg",
  "Toy Story 1.jpg",
  "Toy Story 2.jpg",
  "Toy Story.jpg",
  "Trauma intensifies.jpg",
  "Trisomique.jpg",
  "Une larme 1_ d_eau 99_ de sentiments.jpg",
  "videur vigile portier porte ouvrir door.jpg",
  "Violet snorting water.jpg",
  "Visible Confusion.jpg",
  "Visible frustration plankton.jpg",
  "Voici le fameux mamba les couilles.jpg",
  "Voiture tous les signaux.jpg",
  "Vrai Laink.jpg",
  "Wait. That_s illegal.jpg",
  "Wakanda nonsense is this.jpg",
  "Waluigi.jpg",
  "Wazowski Face Swap 1.jpg",
  "Wazowski Face Swap 2.jpg",
  "We are fucked.jpg",
  "weirdest duck.jpg",
  "What if we use 100_ of our brain.jpg",
  "What the fuck circles.jpg",
  "What the fuck did you just bring upon this cursed land.jpg",
  "What the fuck.jpg",
  "What_s your fucking problem.jpg",
  "Whell that_s retarded.jpg",
  "Will Smith looking at his phone.jpg",
  "Winnie.jpg",
  "Woah hey pal let_s back it up a bit.jpg",
  "Wojak 1.jpg",
  "Wojak 10.jpg",
  "Wojak 11.jpg",
  "Wojak 12.jpg",
  "Wojak 13.jpg",
  "Wojak 14.jpg",
  "Wojak 15.jpg",
  "Wojak 16.jpg",
  "Wojak 17.jpg",
  "Wojak 2.jpg",
  "Wojak 3.jpg",
  "Wojak 4.jpg",
  "Wojak 5.jpg",
  "Wojak 6.jpg",
  "Wojak 6.png",
  "Wojak 7.jpg",
  "Wojak 8.jpg",
  "Wojak 9.jpg",
  "Wojak éloigne.jpg",
  "Wojak sad mask.jpg",
  "Wojak screen.jpg",
  "Wojak smoking.jpg",
  "Wojak suicide.jpg",
  "Worth it.jpg",
  "Wow genius so funny.jpg",
  "Years of academy wasted.jpg",
  "Yes I am Abdul.jpg",
  "Yes.jpg",
  "You are not a clown You are the entire circus.jpg",
  "You are the cutest thing.jpg",
  "You dare oppose me mortal.jpg",
  "You dropped this king.jpg",
  "You dropped this.jpg",
  "You fucking killed her.jpg",
  "You get what you fucking deserve.jpg",
  "You gonna have a bad time.jpg",
  "You have entered the comedy area.jpg",
  "You my love.jpg",
  "You ok no.jpg",
  "You son of a bitch I_m in Morty.jpg",
  "You son of a bitch I_m in Rick.jpg",
  "You unclocked clown outfit.jpg",
  "You were supposed to destroy them.jpg",
  "You_re a man of culture.jpg",
  "You_re a stand user of culture.jpg",
  "Your parent_s best DNA.jpg",
  "Your shoes madam.jpg",
  "Youre Breathtaking.jpg",
  "zebi.jpg",
  "Zootopie.jpg",
  "Zoro.jpg",
];

/**
 * Gets all available meme cards
 */
export function getAllMemeCards(): MemeCard[] {
  if (!memeCardCache) {
    memeCardCache = MEME_FILENAMES.map(createMemeCard);
  }
  return memeCardCache;
}

/**
 * Shuffles an array using Fisher-Yates algorithm
 */
function shuffleArray<T>(array: T[]): T[] {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

/**
 * Gets random meme cards ensuring no duplicates
 * @param count - Number of cards to get
 * @param excludeIds - Array of card IDs to exclude
 * @returns Array of unique meme cards
 */
export function getRandomMemeCards(
  count: number,
  excludeIds: string[] = []
): MemeCard[] {
  const allCards = getAllMemeCards();
  const availableCards = allCards.filter(
    (card) => !excludeIds.includes(card.id)
  );

  if (availableCards.length < count) {
    throw new Error(
      `Not enough unique meme cards available. Requested: ${count}, Available: ${availableCards.length}`
    );
  }

  const shuffled = shuffleArray(availableCards);
  return shuffled.slice(0, count);
}

/**
 * Validates if a meme card filename exists
 */
export function validateMemeCard(filename: string): boolean {
  return MEME_FILENAMES.includes(filename);
}

/**
 * Gets a meme card by filename
 */
export function getMemeCardByFilename(filename: string): MemeCard | null {
  if (!validateMemeCard(filename)) {
    return null;
  }
  return createMemeCard(filename);
}

/**
 * Gets a meme card by ID
 */
export function getMemeCardById(id: string): MemeCard | null {
  const allCards = getAllMemeCards();
  return allCards.find((card) => card.id === id) || null;
}

/**
 * Manages meme card distribution for multiplayer games
 */
export class MemeCardPool {
  private usedCardIds: Set<string> = new Set();

  /**
   * Distributes unique cards to multiple players
   * @param playerCount - Number of players
   * @param cardsPerPlayer - Number of cards per player (default: 7)
   * @returns Map of player index to their cards
   */
  distributeCards(
    playerCount: number,
    cardsPerPlayer: number = 7
  ): Map<number, MemeCard[]> {
    const totalCardsNeeded = playerCount * cardsPerPlayer;
    const allCards = getAllMemeCards();

    if (totalCardsNeeded > allCards.length) {
      throw new Error(
        `Not enough meme cards for ${playerCount} players with ${cardsPerPlayer} cards each. Need: ${totalCardsNeeded}, Available: ${allCards.length}`
      );
    }

    // Reset used cards for new distribution
    this.usedCardIds.clear();

    const shuffledCards = shuffleArray(allCards);
    const distribution = new Map<number, MemeCard[]>();

    for (let playerIndex = 0; playerIndex < playerCount; playerIndex++) {
      const startIndex = playerIndex * cardsPerPlayer;
      const playerCards = shuffledCards.slice(
        startIndex,
        startIndex + cardsPerPlayer
      );

      // Track used cards
      playerCards.forEach((card) => this.usedCardIds.add(card.id));

      distribution.set(playerIndex, playerCards);
    }

    return distribution;
  }

  /**
   * Gets cards for a single player ensuring no duplicates with already distributed cards
   */
  getPlayerCards(cardsPerPlayer: number = 7): MemeCard[] {
    const cards = getRandomMemeCards(
      cardsPerPlayer,
      Array.from(this.usedCardIds)
    );
    // Mark these cards as used
    cards.forEach((card) => this.usedCardIds.add(card.id));
    return cards;
  }

  /**
   * Marks cards as used
   */
  markCardsAsUsed(cardIds: string[]): void {
    cardIds.forEach((id) => this.usedCardIds.add(id));
  }

  /**
   * Resets the pool
   */
  reset(): void {
    this.usedCardIds.clear();
  }

  /**
   * Gets the count of used cards
   */
  getUsedCardCount(): number {
    return this.usedCardIds.size;
  }

  /**
   * Gets the count of available cards
   */
  getAvailableCardCount(): number {
    return getAllMemeCards().length - this.usedCardIds.size;
  }
}
